[package]
name = "dask_planner"
repository = "https://github.com/dask-contrib/dask-sql"
version = "0.1.0"
description = "Bindings for DataFusion used by Dask-SQL"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.59"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync", "fs", "parking_lot"] }
rand = "0.7"
pyo3 = { version = "0.16", features = ["extension-module", "abi3", "abi3-py38"] }
arrow = { version = "19.0.0", features = ["prettyprint"] }
datafusion-sql = { git="https://github.com/apache/arrow-datafusion/", rev = "e23925c96c97139d101719fa7a456088eeed6ae9" }
datafusion-expr = { git="https://github.com/apache/arrow-datafusion/", rev = "e23925c96c97139d101719fa7a456088eeed6ae9" }
datafusion-common = { git="https://github.com/apache/arrow-datafusion/", rev = "e23925c96c97139d101719fa7a456088eeed6ae9" }
datafusion-optimizer = { git="https://github.com/apache/arrow-datafusion/", rev = "e23925c96c97139d101719fa7a456088eeed6ae9" }
uuid = { version = "0.8", features = ["v4"] }
mimalloc = { version = "*", default-features = false }
parking_lot = "0.12"
async-trait = "0.1.41"
sqlparser = "0.18"


[lib]
crate-type = ["cdylib"]
