name: Upload Page

on:
  push:
    branches: ["gh-pages"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run export

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          rm -rf docs
          mv ./out ./docs
          git add ./docs
          git commit -m "Deployment" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

